development:
  adapter: postgresql
  database: colchonet_dev
  host: localhost
  username: elias
  password: 159357123
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: colchonet_test
  host: localhost
  username: elias
  password: 159357123
  pool: 5
  timeout: 5000